
platform :ios, '10.0'

target 'TuyaCommunityKitSample' do
  pod 'TuyaCommunityKit'
  pod 'Masonry'
  pod 'MBProgressHUD'

end

# supports M1
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
